headers = {
    "authority": "api.arkhamintelligence.com",
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9,ru-RU;q=0.8,ru;q=0.7",
    "authorization": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkMDNhZTdmNDczZjJjNmIyNTI3NmMwNjM2MGViOTk4ODdlMjNhYTkiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiS2VscDFlIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2Fya2hhbS1kZXYtMjgxNDIzIiwiYXVkIjoiYXJraGFtLWRldi0yODE0MjMiLCJhdXRoX3RpbWUiOjE2ODc1ODM4ODAsInVzZXJfaWQiOiJGZzJSUlY5cU9HVGNRc28zR01iYmZQclgxMnIxIiwic3ViIjoiRmcyUlJWOXFPR1RjUXNvM0dNYmJmUHJYMTJyMSIsImlhdCI6MTY4NzYyNzE2MCwiZXhwIjoxNjg3NjMwNzYwLCJlbWFpbCI6InZsYWRrbHAyMkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidmxhZGtscDIyQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.QPPxw4Y8eRLz-av4vpY41i1c81wLhQl5WKStYi2QX96tFMVJbaM-zuI1Q29GAX-KT3rCzPpSZxKohrkm3506l_hS38yMQUVYDdnAZQwNCWhNj7F5Jz0R9KiY9YvXyiL7wk22pZnap3B79KWiStpA6rVpTxsFPcTl-WklZ2WgBA-tVYKc1H-h8sN4kjH0CbqOsUnBVEIjkCt7Brs05FGt9N0OtfpEck6N6X8MMHdijkMHHDwAqMvs6EbQjeH-XuJ-TFe8AkqtR3Wely3_8QxWKTx5hkll60SVrC3DDflDLWDeN8rCn4bqiox0t9ZIigR0vz_twu0kObeRrELF-cc8WA",
    "cache-control": "no-cache",
    "origin": "https://platform.arkhamintelligence.com",
    "pragma": "no-cache",
    "referer": "https://platform.arkhamintelligence.com/",
    "sec-ch-ua": '"Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
}
